create table CDYMS( 
date_t date Primary Key, 
shift varchar(1) Primary Key, 
shift_engineer_1 varchar(100), 
shift_engineer_2 varchar(100), 
AS_STATUS varchar(100),
AS_STATUS_remarks varchar(100),
DS_STATUS varchar(100),
DS_STATUS_remarks varchar(100),
firewall_status1 varchar(15), 
firewall_status2 varchar(15), 
firewall_status1_remarks varchar(150), 
firewall_status2_remarks varchar(150), 
wac_status1 varchar(15), 
wac_status1_RE varchar(150), 
wac_status2 varchar(15), 
wac_status2_RE varchar(150), 
access_points_status varchar(15), 
access_points_status_RE varchar(150), 
hhts_status varchar(15), 
hhts_status_RE varchar(150), 
gps_devices_status varchar(15,) 
gps_devices_status_RE varchar(150), 
ups_status varchar(15), 
ups_status_RE varchar(150),  
server_room_temp_time time, 
server_room_temp_time_RE varchar(150), 
server_room_temp_value varchar(20), 
server_room_temp_value_RE varchar(150), 
any_other_info varchar(200)
);